# TEMPLATE

name: auth_client
description: Starting point for a Serverpod client.

environment:
  sdk: DART_VERSION

dependencies:
  serverpod_client: SERVERPOD_VERSION 
  serverpod_auth_idp_client: SERVERPOD_VERSION

dev_dependencies:
  serverpod_lints: 3.0.0-alpha.3

dependency_overrides: 
  serverpod_auth_idp_client:
    path: ../../../modules/new_serverpod_auth/serverpod_auth_idp/serverpod_auth_idp_client
  serverpod_auth_core_client:
    path: ../../../modules/new_serverpod_auth/serverpod_auth_core/serverpod_auth_core_client
  serverpod_client:
    path: ../../../packages/serverpod_client
  serverpod_serialization:
    path: ../../../packages/serverpod_serialization
  serverpod_lints:
    path: ../../../packages/serverpod_lints
