# TEMPLATE

name: chat_client
description: Starting point for a Serverpod client.

environment:
  sdk: DART_VERSION

dependencies:
  serverpod_client: SERVERPOD_VERSION
  serverpod_auth_client: SERVERPOD_VERSION
  serverpod_chat_client: SERVERPOD_VERSION

dev_dependencies:
  serverpod_lints: 3.0.0-alpha.3

dependency_overrides:
  serverpod_client:
    path: ../../../packages/serverpod_client
  serverpod_auth_client:
    path: ../../../modules/serverpod_auth/serverpod_auth_client
  serverpod_chat_client:
    path: ../../../modules/serverpod_chat/serverpod_chat_client
  serverpod_serialization:
    path: ../../../packages/serverpod_serialization
  serverpod_lints:
    path: ../../../packages/serverpod_lints
