# TEMPLATE

name: chat_server
description: Starting point for a Serverpod server.

environment:
  sdk: DART_VERSION

dependencies:
  serverpod: SERVERPOD_VERSION
  serverpod_auth_server: SERVERPOD_VERSION
  serverpod_chat_server: SERVERPOD_VERSION

dev_dependencies:
  serverpod_lints: SERVERPOD_VERSION

dependency_overrides:
  serverpod:
    path: ../../../packages/serverpod
  serverpod_auth_server:
    path: ../../../modules/serverpod_auth/serverpod_auth_server
  serverpod_chat_server:
    path: ../../../modules/serverpod_chat/serverpod_chat_server
  serverpod_serialization:
    path: ../../../packages/serverpod_serialization
  serverpod_shared:
    path: ../../../packages/serverpod_shared
  serverpod_lints:
    path: ../../../packages/serverpod_lints
